export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const LIKE_POST = "LIKE_POST";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const GET_POST_BY_SEARCH = 'GET_POST_BY_SEARCH';
export const START_LOADING = "START_LOADING";
export const END_LOADING = "END_LOADING";

export const GET_USER_POSTS = 'GET_USER_POSTS';
export const SAVE_POST = 'SAVE_POST';
export const GET_SAVED_POSTS = 'GET_SAVED_POSTS';